function plugins = registerBuiltinPlugins()
% registerBuiltinPlugins - Built-in signal pipeline plugins.

    plugins = [ ...
        snap_modules.plugins.signal.processing_builtin(), ...
        snap_modules.plugins.signal.maxima_detection_builtin(), ...
        snap_modules.plugins.signal.gaussian_fitting_builtin(), ...
        snap_modules.plugins.signal.fit_filtering_builtin(), ...
        snap_modules.plugins.signal.classification_builtin(), ...
        snap_modules.plugins.signal.nuclei_filtering_builtin() ...
    ];
end
