function pack = buildExpressionPack(varargin)
% buildExpressionPack - Build a per-channel SVM expression pack for SNAP.
%
% This is an example contribution that expands beyond the default
% "all non-position base features" behavior by adding a curated set of
% scientifically motivated custom expressions.
%
% Usage:
%   pack = snap_contrib.svm.buildExpressionPack('ParameterFile', 'params.mat');
%   pack = snap_contrib.svm.buildExpressionPack('ParameterStruct', paramsStruct);
%
% Name-value options:
%   'ParameterFile'                - SNAP parameter MAT file
%   'ParameterStruct'              - already-loaded parameter struct
%   'Channels'                     - channel indices to include (default: all)
%   'IncludeAdvancedStatsFeatures' - include model-selection/statistical
%                                    base features produced by
%                                    snap_contrib.svm.augmentFitResultsWithModelStats
%   'SelectionMode'                - base-feature selection strategy:
%                                      'focused' (default): prioritized compact subset
%                                      'all_non_position': all non-position features
%
% Output:
%   pack - struct with per-channel selectedFeatures/customExpressions.

    p = inputParser;
    p.addParameter('ParameterFile', '', @(x) ischar(x) || isstring(x));
    p.addParameter('ParameterStruct', struct(), @isstruct);
    p.addParameter('Channels', [], @(x) isempty(x) || (isnumeric(x) && isvector(x)));
    p.addParameter('IncludeAdvancedStatsFeatures', false, @(x) islogical(x) || isnumeric(x));
    p.addParameter('SelectionMode', 'focused', @(x) ischar(x) || isstring(x));
    p.parse(varargin{:});
    opts = p.Results;
    selectionMode = lower(strtrim(char(string(opts.SelectionMode))));
    if ~ismember(selectionMode, {'focused', 'all_non_position'})
        error('buildExpressionPack:InvalidSelectionMode', ...
            'SelectionMode must be ''focused'' or ''all_non_position''.');
    end

    params = opts.ParameterStruct;
    parameterSource = 'ParameterStruct';

    if isempty(fieldnames(params))
        parameterFile = strtrim(char(string(opts.ParameterFile)));
        if isempty(parameterFile)
            error('buildExpressionPack:MissingParameters', ...
                'Provide either ParameterStruct or ParameterFile.');
        end
        [params, meta] = snap_helpers.classification.loadParameterStruct(parameterFile);
        parameterSource = parameterFile;
    else
        [params, meta] = snap_helpers.classification.loadParameterStruct(params);
    end

    [allCaps, capMeta] = snap_helpers.classification.resolveChannelCapabilities(params, ...
        'IncludeFeatureInfo', true, ...
        'HasPhysicalSpacing', false);
    numChannels = numel(allCaps);

    channels = [allCaps.channelIdx];
    if ~isempty(opts.Channels)
        channels = unique(round(opts.Channels(:)'));
        channels = channels(channels >= 1 & channels <= numChannels);
        if isempty(channels)
            error('buildExpressionPack:InvalidChannels', ...
                'No valid channels selected. Valid range is 1..%d.', numChannels);
        end
    end

    includeAdvanced = logical(opts.IncludeAdvancedStatsFeatures);
    advancedStatsFeatures = localAdvancedStatsFeatureNames();
    exprLibrary = localExpressionLibrary();

    channelPacks = repmat(struct( ...
        'channelIdx', 1, ...
        'fittingMethod', '', ...
        'has3D', true, ...
        'selectedFeatures', {{}}, ...
        'customExpressions', struct('name', {}, 'expression', {}, 'requiredFeatures', {}, 'requiredCapabilities', {}), ...
        'requiredFeatures', {{}}, ...
        'requiredCapabilities', struct('fittingMethod', '', 'has3D', [], 'hasPhysicalSpacing', []), ...
        'advancedStatsFeatureNames', {{}}, ...
        'notes', ''), 1, numel(channels));

    for i = 1:numel(channels)
        ch = channels(i);
        capIdx = find([allCaps.channelIdx] == ch, 1, 'first');
        if isempty(capIdx)
            error('buildExpressionPack:ChannelResolutionError', ...
                'Could not resolve feature capabilities for channel %d.', ch);
        end

        cap = allCaps(capIdx);
        allFeatures = cap.availableFeatures;
        featureInfo = cap.featureInfo;
        fittingMethod = cap.fittingMethod;
        has3D = logical(cap.has3D);

        selected = localSelectBaseFeatures(allFeatures, featureInfo, fittingMethod, has3D, selectionMode);
        if includeAdvanced
            selected = unique([selected, advancedStatsFeatures], 'stable');
        end

        availableSet = unique([allFeatures, selected], 'stable');
        customExpressions = localSelectExpressions(exprLibrary, availableSet, fittingMethod, has3D);
        requiredFeatures = unique([selected, localCollectExpressionRequiredFeatures(customExpressions)], 'stable');

        channelPacks(i).channelIdx = ch;
        channelPacks(i).fittingMethod = fittingMethod;
        channelPacks(i).has3D = has3D;
        channelPacks(i).selectedFeatures = selected;
        channelPacks(i).customExpressions = customExpressions;
        channelPacks(i).requiredFeatures = requiredFeatures;
        channelPacks(i).requiredCapabilities = struct( ...
            'fittingMethod', fittingMethod, ...
            'has3D', has3D, ...
            'hasPhysicalSpacing', false);
        if includeAdvanced
            channelPacks(i).advancedStatsFeatureNames = advancedStatsFeatures;
            channelPacks(i).notes = sprintf([ ...
                'Includes optional model-stat features from ', ...
                'snap_contrib.svm.augmentFitResultsWithModelStats.']);
        else
            channelPacks(i).advancedStatsFeatureNames = {};
            channelPacks(i).notes = 'UI-compatible expression set using canonical SNAP features only.';
        end
    end

    pack = struct();
    pack.specVersion = '2.0.0';
    pack.packId = 'snap_literature_informed_svm_pack';
    pack.minSnapVersion = '1.1.0';
    pack.strictModeDefault = false;
    pack.name = 'SNAP Literature-Informed SVM Expression Pack';
    pack.version = '2.0.0';
    pack.generatedOn = datestr(now, 'yyyy-mm-dd HH:MM:SS');
    pack.parameterSource = parameterSource;
    pack.parameterContainer = meta.container;
    pack.parameterWarnings = meta.warnings;
    pack.numChannelsDetected = numChannels;
    pack.channelsIncluded = channels;
    pack.includeAdvancedStatsFeatures = includeAdvanced;
    pack.selectionMode = selectionMode;
    pack.description = [ ...
        'Example contribution pack with channel-aware curated expressions and ', ...
        'capability metadata for safe validation against SNAP parameter files.'];
    pack.references = localLiteratureReferences();
    pack.channelResolutionMeta = capMeta;
    pack.channelPacks = channelPacks;
    pack.rationale = [ ...
        'Expressions emphasize dynamic-range stabilization (log transforms), ', ...
        'signal-vs-background normalization, PSF/shape compactness, anisotropy, ', ...
        'and fit-quality coupling.'];
end

function selected = localNonPositionFeatures(allFeatures, featureInfo)
    selected = {};
    for i = 1:numel(allFeatures)
        f = allFeatures{i};
        if isfield(featureInfo, f) && isfield(featureInfo.(f), 'category') && ...
                strcmpi(featureInfo.(f).category, 'position')
            continue;
        end
        selected{end+1} = f; %#ok<AGROW>
    end
end

function selected = localSelectBaseFeatures(allFeatures, featureInfo, fittingMethod, has3D, selectionMode)
    if nargin < 5 || isempty(selectionMode)
        selectionMode = 'focused';
    end
    selectionMode = lower(strtrim(char(string(selectionMode))));

    allNonPosition = localNonPositionFeatures(allFeatures, featureInfo);
    if strcmp(selectionMode, 'all_non_position')
        selected = allNonPosition;
        return;
    end

    methodKey = localFocusedProfileKey(fittingMethod, has3D);
    prioritized = localFocusedFeatureProfile(methodKey);
    selected = unique(prioritized, 'stable');
    selected = selected(ismember(selected, allNonPosition));

    if isempty(selected)
        selected = localLegacyFocusedSelection(allFeatures, fittingMethod, has3D);
        selected = unique(selected, 'stable');
        selected = selected(ismember(selected, allNonPosition));
    end

    if isempty(selected)
        selected = allNonPosition;
    end
end

function methodKey = localFocusedProfileKey(fittingMethod, has3D)
    fm = lower(strtrim(char(string(fittingMethod))));

    if contains(fm, 'radial symmetry')
        methodKey = 'radial_symmetry';
        return;
    end
    if contains(fm, '2d (xy) + 1d (z)') || contains(fm, '2d+1d')
        methodKey = 'gaussian_2d_plus_1d';
        return;
    end
    if contains(fm, '1d (x,y,z)') || contains(fm, '1d x,y,z')
        methodKey = 'gaussian_1d_xyz';
        return;
    end
    if contains(fm, 'skewed')
        if has3D
            methodKey = 'skewed_3d';
        else
            methodKey = 'skewed_2d';
        end
        return;
    end
    if contains(fm, 'distorted')
        if has3D
            methodKey = 'distorted_3d';
        else
            methodKey = 'distorted_2d';
        end
        return;
    end
    if contains(fm, '2d gaussian')
        methodKey = 'gaussian_2d';
        return;
    end
    if contains(fm, '3d gaussian')
        methodKey = 'gaussian_3d';
        return;
    end

    if has3D
        methodKey = 'gaussian_3d';
    else
        methodKey = 'gaussian_2d';
    end
end

function prioritized = localFocusedFeatureProfile(methodKey)
    core = {'integrated_intensity', 'background', 'snr'};

    switch methodKey
        case 'distorted_3d'
            % IMPORTANT: keep Distorted 3D focused profile unchanged.
            prioritized = [core, { ...
                'r_squared', 'amplitude', ...
                'sigma_x', 'sigma_y', 'sigma_z', ...
                'sigma_sum', 'sigma_product', 'sigma_xy_ratio', 'sigma_z_ratio', ...
                'amplitude_over_background', ...
                'rho_xy', 'rho_xz', 'rho_yz'}];

        case 'distorted_2d'
            prioritized = [core, { ...
                'r_squared', 'amplitude', ...
                'sigma_x', 'sigma_y', ...
                'sigma_sum', 'sigma_product', 'sigma_xy_ratio', ...
                'amplitude_over_background', 'rho_xy'}];

        case 'skewed_3d'
            prioritized = [core, { ...
                'r_squared', 'amplitude', ...
                'sigma_x', 'sigma_y', 'sigma_z', ...
                'sigma_sum', 'sigma_product', 'sigma_xy_ratio', 'sigma_z_ratio', ...
                'amplitude_over_background', ...
                'rho_xy', 'rho_xz', 'rho_yz', ...
                'alpha_x', 'alpha_y', 'alpha_z'}];

        case 'skewed_2d'
            prioritized = [core, { ...
                'r_squared', 'amplitude', ...
                'sigma_x', 'sigma_y', ...
                'sigma_sum', 'sigma_product', 'sigma_xy_ratio', ...
                'amplitude_over_background', ...
                'alpha_x', 'alpha_y'}];

        case 'gaussian_3d'
            prioritized = [core, { ...
                'r_squared', 'amplitude', ...
                'sigma_x', 'sigma_y', 'sigma_z', ...
                'sigma_sum', 'sigma_product', 'sigma_xy_ratio', 'sigma_z_ratio', ...
                'amplitude_over_background'}];

        case 'gaussian_2d'
            prioritized = [core, { ...
                'r_squared', 'amplitude', ...
                'sigma_x', 'sigma_y', ...
                'sigma_sum', 'sigma_product', 'sigma_xy_ratio', ...
                'amplitude_over_background'}];

        case 'gaussian_1d_xyz'
            prioritized = [core, { ...
                'r_squared', 'amplitude', ...
                'amplitude_x', 'amplitude_y', 'amplitude_z', ...
                'sigma_x', 'sigma_y', 'sigma_z', ...
                'sigma_sum', 'sigma_product', 'sigma_xy_ratio', 'sigma_z_ratio'}];

        case 'gaussian_2d_plus_1d'
            prioritized = [core, { ...
                'r_squared', ...
                'amplitude_xy', 'amplitude_z', ...
                'sigma_x', 'sigma_y', 'sigma_z', ...
                'sigma_sum', 'sigma_product', 'sigma_xy_ratio', 'sigma_z_ratio'}];

        case 'radial_symmetry'
            prioritized = [core, {'radial_symmetry_score'}];

        otherwise
            prioritized = {};
    end
end

function prioritized = localLegacyFocusedSelection(allFeatures, fittingMethod, has3D)
    prioritized = {};

    if ismember('integrated_intensity', allFeatures)
        prioritized{end+1} = 'integrated_intensity'; %#ok<AGROW>
    end
    if ismember('background', allFeatures)
        prioritized{end+1} = 'background'; %#ok<AGROW>
    end
    if ismember('snr', allFeatures)
        prioritized{end+1} = 'snr'; %#ok<AGROW>
    end

    if ismember('r_squared', allFeatures)
        prioritized{end+1} = 'r_squared'; %#ok<AGROW>
    elseif ismember('radial_symmetry_score', allFeatures)
        prioritized{end+1} = 'radial_symmetry_score'; %#ok<AGROW>
    end

    amplitudeCandidates = {'amplitude', 'amplitude_xy', 'amplitude_z', 'amplitude_x', 'amplitude_y'};
    for i = 1:numel(amplitudeCandidates)
        if ismember(amplitudeCandidates{i}, allFeatures)
            prioritized{end+1} = amplitudeCandidates{i}; %#ok<AGROW>
        end
    end

    sigmaCandidates = {'sigma_x', 'sigma_y', 'sigma_z', 'sigma_sum', 'sigma_product', 'sigma_xy_ratio', 'sigma_z_ratio'};
    for i = 1:numel(sigmaCandidates)
        if ismember(sigmaCandidates{i}, allFeatures)
            prioritized{end+1} = sigmaCandidates{i}; %#ok<AGROW>
        end
    end

    if ismember('amplitude_over_background', allFeatures)
        prioritized{end+1} = 'amplitude_over_background'; %#ok<AGROW>
    end

    if contains(lower(fittingMethod), 'distorted') || contains(lower(fittingMethod), 'skewed')
        rhoCandidates = {'rho_xy', 'rho_xz', 'rho_yz'};
        for i = 1:numel(rhoCandidates)
            if ismember(rhoCandidates{i}, allFeatures)
                prioritized{end+1} = rhoCandidates{i}; %#ok<AGROW>
            end
        end
    end

    if has3D && ismember('sigma_z', allFeatures) && ~ismember('sigma_z', prioritized)
        prioritized{end+1} = 'sigma_z'; %#ok<AGROW>
    end
end

function expressions = localSelectExpressions(exprLibrary, availableFeatures, fittingMethod, has3D)
    if isempty(exprLibrary)
        expressions = struct('name', {}, 'expression', {}, 'requiredFeatures', {}, 'requiredCapabilities', {});
        return;
    end

    availableSet = string(availableFeatures);
    expressions = struct('name', {}, 'expression', {}, 'requiredFeatures', {}, 'requiredCapabilities', {});
    addedNames = strings(0, 1);

    for i = 1:numel(exprLibrary)
        req = string(exprLibrary(i).requiredFeatures);
        if ~all(ismember(req, availableSet))
            continue;
        end

        exprName = string(exprLibrary(i).name);
        if any(exprName == addedNames)
            continue;
        end

        expressions(end+1) = struct( ... %#ok<AGROW>
            'name', char(exprLibrary(i).name), ...
            'expression', char(exprLibrary(i).expression), ...
            'requiredFeatures', {cellstr(string(exprLibrary(i).requiredFeatures(:)'))}, ...
            'requiredCapabilities', struct('fittingMethod', fittingMethod, 'has3D', logical(has3D)));
        addedNames(end+1, 1) = exprName; %#ok<AGROW>
    end
end

function requiredFeatures = localCollectExpressionRequiredFeatures(customExpressions)
    requiredFeatures = {};
    for i = 1:numel(customExpressions)
        if isfield(customExpressions(i), 'requiredFeatures')
            requiredFeatures = [requiredFeatures, customExpressions(i).requiredFeatures]; %#ok<AGROW>
        end
    end
    requiredFeatures = unique(requiredFeatures, 'stable');
end

function names = localAdvancedStatsFeatureNames()
    names = snap_helpers.classification.getModelStatsFeatureNames();
end

function lib = localExpressionLibrary()
    lib = struct('name', {}, 'expression', {}, 'requiredFeatures', {}, 'rationale', {});

    % Signal/background transforms (dynamic-range stabilized)
    lib(end+1) = localExpr('log_integrated_intensity', ...
        'log10(max(integrated_intensity + 1, 1e-6))', ...
        {'integrated_intensity'}, ...
        'Stabilizes heavy-tailed spot intensity distributions.');
    lib(end+1) = localExpr('log_background', ...
        'log10(max(background + 1, 1e-6))', ...
        {'background'}, ...
        'Compresses local background dynamic range.');
    lib(end+1) = localExpr('log_snr_proxy', ...
        'log10(max((integrated_intensity + 1) / (background + 1), 1e-6))', ...
        {'integrated_intensity', 'background'}, ...
        'Background-normalized signal proxy with log compression.');
    lib(end+1) = localExpr('poisson_snr_proxy', ...
        '(integrated_intensity - background) / sqrt(max(integrated_intensity + background, 1))', ...
        {'integrated_intensity', 'background'}, ...
        'Poisson-like contrast proxy using signal+background variance scaling.');
    lib(end+1) = localExpr('shot_noise_proxy', ...
        '(integrated_intensity - background) / sqrt(max(background, 0) + 1)', ...
        {'integrated_intensity', 'background'}, ...
        'Approximate Poisson-dominated contrast score.');
    lib(end+1) = localExpr('background_fraction', ...
        'background / (integrated_intensity + background + 1)', ...
        {'integrated_intensity', 'background'}, ...
        'Fraction of local intensity explained by background.');
    lib(end+1) = localExpr('signal_fraction', ...
        'integrated_intensity / (integrated_intensity + background + 1)', ...
        {'integrated_intensity', 'background'}, ...
        'Fraction of total local intensity assigned to spot signal.');
    lib(end+1) = localExpr('contrast_to_background', ...
        '(integrated_intensity - background) / (background + 1)', ...
        {'integrated_intensity', 'background'}, ...
        'Classical local contrast ratio.');
    lib(end+1) = localExpr('background_subtracted_log_signal', ...
        'log10(max(integrated_intensity - background + 1, 1e-6))', ...
        {'integrated_intensity', 'background'}, ...
        'Log-compressed signal after background subtraction.');
    lib(end+1) = localExpr('inverse_bg_penalty', ...
        'integrated_intensity / ((background + 1)^2)', ...
        {'integrated_intensity', 'background'}, ...
        'Intensity penalized quadratically by background burden.');

    % Fit-quality couplings
    lib(end+1) = localExpr('quality_weighted_snr', ...
        'r_squared * log10(max((integrated_intensity + 1) / (background + 1), 1e-6))', ...
        {'r_squared', 'integrated_intensity', 'background'}, ...
        'Couples fit quality and normalized signal strength.');
    lib(end+1) = localExpr('quality_penalty', ...
        '(1 - r_squared) * log10(max(integrated_intensity + 1, 1e-6))', ...
        {'r_squared', 'integrated_intensity'}, ...
        'Penalizes bright but poorly fit detections.');
    lib(end+1) = localExpr('quality_bg_compound', ...
        'r_squared * (integrated_intensity / (background + 1))', ...
        {'r_squared', 'integrated_intensity', 'background'}, ...
        'High when both fit quality and background-normalized intensity are high.');
    lib(end+1) = localExpr('quality_vs_size_penalty', ...
        'r_squared / (sigma_sum + 1e-3)', ...
        {'r_squared', 'sigma_sum'}, ...
        'Rewards compact, high-quality fits.');
    lib(end+1) = localExpr('snr_vs_size_penalty', ...
        'snr / (sigma_sum + 1e-3)', ...
        {'snr', 'sigma_sum'}, ...
        'SNR penalized by broad spatial footprint.');
    lib(end+1) = localExpr('snr_quality_harmonic', ...
        '2 / ((1 / max(snr, 1e-3)) + (1 / max(r_squared, 1e-3)))', ...
        {'snr', 'r_squared'}, ...
        'Harmonic coupling of SNR and fit quality (penalizes imbalance).');
    lib(end+1) = localExpr('quality_bg_penalty', ...
        'r_squared / (background + 1)', ...
        {'r_squared', 'background'}, ...
        'Penalizes otherwise good fits in high local background.');
    lib(end+1) = localExpr('quality_signal_fraction', ...
        'r_squared * (integrated_intensity / (integrated_intensity + background + 1))', ...
        {'r_squared', 'integrated_intensity', 'background'}, ...
        'Joint score for fit quality and local signal purity.');
    lib(end+1) = localExpr('quality_signal_harmonic_fraction', ...
        '2 / ((1 / max(r_squared, 1e-3)) + (1 / max(integrated_intensity / (integrated_intensity + background + 1), 1e-3)))', ...
        {'r_squared', 'integrated_intensity', 'background'}, ...
        'Harmonic coupling of fit quality and local signal-purity fraction.');

    % Morphology / compactness descriptors
    lib(end+1) = localExpr('ellipticity_log', ...
        'abs(log(max((abs(sigma_x) + 1e-3) / (abs(sigma_y) + 1e-3), 1e-6)))', ...
        {'sigma_x', 'sigma_y'}, ...
        'Shape anisotropy magnitude in XY.');
    lib(end+1) = localExpr('ellipticity_ratio_xy', ...
        '(abs(sigma_x) + 1e-3) / (abs(sigma_y) + 1e-3)', ...
        {'sigma_x', 'sigma_y'}, ...
        'Raw XY sigma ratio (ellipticity).');
    lib(end+1) = localExpr('psf_roundness_penalty', ...
        'abs(sigma_x - sigma_y) / (sigma_x + sigma_y + 1e-3)', ...
        {'sigma_x', 'sigma_y'}, ...
        'Dimensionless PSF roundness deviation in XY.');
    lib(end+1) = localExpr('psf_roundness_score', ...
        '1 / (1 + abs(sigma_x - sigma_y) / (sigma_x + sigma_y + 1e-3))', ...
        {'sigma_x', 'sigma_y'}, ...
        'Higher when lateral PSF widths are balanced.');
    lib(end+1) = localExpr('compactness_2d', ...
        'integrated_intensity / (sigma_x * sigma_y + 1e-3)', ...
        {'integrated_intensity', 'sigma_x', 'sigma_y'}, ...
        'Intensity concentration per estimated PSF area.');
    lib(end+1) = localExpr('size_penalized_snr_2d', ...
        'log10(max((integrated_intensity + 1) / (background + 1), 1e-6)) / (sigma_x + sigma_y + 1e-3)', ...
        {'integrated_intensity', 'background', 'sigma_x', 'sigma_y'}, ...
        'Normalized signal penalized by broad PSF widths.');
    lib(end+1) = localExpr('quality_per_sigma_sum_2d', ...
        'r_squared / (sigma_x + sigma_y + 1e-3)', ...
        {'r_squared', 'sigma_x', 'sigma_y'}, ...
        'Fit quality normalized by spot footprint.');
    lib(end+1) = localExpr('quality_compactness_coupled_2d', ...
        'r_squared * integrated_intensity / (sigma_x * sigma_y + background + 1)', ...
        {'r_squared', 'integrated_intensity', 'sigma_x', 'sigma_y', 'background'}, ...
        '2D quality-intensity score penalized by spread and local background.');
    lib(end+1) = localExpr('intensity_over_sigma_product', ...
        'integrated_intensity / (sigma_product + 1e-3)', ...
        {'integrated_intensity', 'sigma_product'}, ...
        'Signal concentration using derived sigma-product.');
    lib(end+1) = localExpr('sigma_product_over_intensity', ...
        'sigma_product / (integrated_intensity + 1)', ...
        {'sigma_product', 'integrated_intensity'}, ...
        'Inverse concentration measure; high for diffuse spots.');
    lib(end+1) = localExpr('sigma_sum_over_intensity', ...
        'sigma_sum / (integrated_intensity + 1)', ...
        {'sigma_sum', 'integrated_intensity'}, ...
        'Diffuse-width penalty relative to signal.');
    lib(end+1) = localExpr('thompson_var_xy_proxy', ...
        '(((sigma_x^2 + sigma_y^2) / 2) + (1/12)) / max(integrated_intensity, 1) + (8 * pi * (((sigma_x^2 + sigma_y^2) / 2)^2) * (background^2)) / (max(integrated_intensity, 1)^2)', ...
        {'sigma_x', 'sigma_y', 'integrated_intensity', 'background'}, ...
        'Localization-variance proxy inspired by Thompson et al. (2002).');
    lib(end+1) = localExpr('thompson_precision_xy_proxy', ...
        'sqrt(max(((((sigma_x^2 + sigma_y^2) / 2) + (1/12)) / max(integrated_intensity, 1) + (8 * pi * (((sigma_x^2 + sigma_y^2) / 2)^2) * (background^2)) / (max(integrated_intensity, 1)^2)), 1e-12))', ...
        {'sigma_x', 'sigma_y', 'integrated_intensity', 'background'}, ...
        'Square-root localization precision proxy in XY.');
    lib(end+1) = localExpr('thompson_information_xy', ...
        '1 / (sqrt(max(((((sigma_x^2 + sigma_y^2) / 2) + (1/12)) / max(integrated_intensity, 1) + (8 * pi * (((sigma_x^2 + sigma_y^2) / 2)^2) * (background^2)) / (max(integrated_intensity, 1)^2)), 1e-12)) + 1e-6)', ...
        {'sigma_x', 'sigma_y', 'integrated_intensity', 'background'}, ...
        'Inverse XY precision proxy (higher implies better localization information).');
    lib(end+1) = localExpr('localization_information_density_xy', ...
        '(1 / (sqrt(max(((((sigma_x^2 + sigma_y^2) / 2) + (1/12)) / max(integrated_intensity, 1) + (8 * pi * (((sigma_x^2 + sigma_y^2) / 2)^2) * (background^2)) / (max(integrated_intensity, 1)^2)), 1e-12)) + 1e-6)) / (sigma_x + sigma_y + 1e-3)', ...
        {'sigma_x', 'sigma_y', 'integrated_intensity', 'background'}, ...
        'Localization-information proxy per lateral spread unit.');

    % 3D anisotropy terms
    lib(end+1) = localExpr('compactness_3d', ...
        'integrated_intensity / (sigma_x * sigma_y * sigma_z + 1e-3)', ...
        {'integrated_intensity', 'sigma_x', 'sigma_y', 'sigma_z'}, ...
        'Intensity concentration per estimated PSF volume.');
    lib(end+1) = localExpr('z_anisotropy_abs', ...
        'abs(log(max((abs(sigma_z) + 1e-3) / (((abs(sigma_x) + abs(sigma_y)) / 2) + 1e-3), 1e-6)))', ...
        {'sigma_x', 'sigma_y', 'sigma_z'}, ...
        'Axial-vs-lateral anisotropy magnitude.');
    lib(end+1) = localExpr('size_penalized_snr_3d', ...
        'log10(max((integrated_intensity + 1) / (background + 1), 1e-6)) / (sigma_x + sigma_y + sigma_z + 1e-3)', ...
        {'integrated_intensity', 'background', 'sigma_x', 'sigma_y', 'sigma_z'}, ...
        '3D normalized signal penalized by total width.');
    lib(end+1) = localExpr('sigma_z_compactness', ...
        'sigma_z / (sigma_x + sigma_y + 1e-3)', ...
        {'sigma_x', 'sigma_y', 'sigma_z'}, ...
        'Relative axial broadening.');
    lib(end+1) = localExpr('quality_anisotropy_3d', ...
        'r_squared / (abs(log(max((abs(sigma_z) + 1e-3) / (((abs(sigma_x) + abs(sigma_y))/2) + 1e-3), 1e-6))) + 1)', ...
        {'r_squared', 'sigma_x', 'sigma_y', 'sigma_z'}, ...
        'Quality penalized by excessive axial anisotropy.');
    lib(end+1) = localExpr('thompson_var_z_proxy', ...
        '(sigma_z^2 + (1/12)) / max(integrated_intensity, 1) + (8 * pi * (sigma_z^4) * (background^2)) / (max(integrated_intensity, 1)^2)', ...
        {'sigma_z', 'integrated_intensity', 'background'}, ...
        'Axial localization-variance proxy inspired by Thompson-style scaling.');
    lib(end+1) = localExpr('thompson_precision_z_proxy', ...
        'sqrt(max(((sigma_z^2 + (1/12)) / max(integrated_intensity, 1) + (8 * pi * (sigma_z^4) * (background^2)) / (max(integrated_intensity, 1)^2)), 1e-12))', ...
        {'sigma_z', 'integrated_intensity', 'background'}, ...
        'Square-root axial precision proxy.');
    lib(end+1) = localExpr('thompson_information_z', ...
        '1 / (sqrt(max(((sigma_z^2 + (1/12)) / max(integrated_intensity, 1) + (8 * pi * (sigma_z^4) * (background^2)) / (max(integrated_intensity, 1)^2)), 1e-12)) + 1e-6)', ...
        {'sigma_z', 'integrated_intensity', 'background'}, ...
        'Inverse axial precision proxy.');
    lib(end+1) = localExpr('axial_to_lateral_precision_ratio', ...
        '(sqrt(max(((sigma_z^2 + (1/12)) / max(integrated_intensity, 1) + (8 * pi * (sigma_z^4) * (background^2)) / (max(integrated_intensity, 1)^2)), 1e-12))) / (sqrt(max(((((sigma_x^2 + sigma_y^2) / 2) + (1/12)) / max(integrated_intensity, 1) + (8 * pi * (((sigma_x^2 + sigma_y^2) / 2)^2) * (background^2)) / (max(integrated_intensity, 1)^2)), 1e-12)) + 1e-6)', ...
        {'sigma_x', 'sigma_y', 'sigma_z', 'integrated_intensity', 'background'}, ...
        'Relative axial-vs-lateral localization precision proxy.');

    % Amplitude-centric descriptors
    lib(end+1) = localExpr('amp_bg_log', ...
        'log10(max(amplitude + 1, 1e-6)) - log10(max(background + 1, 1e-6))', ...
        {'amplitude', 'background'}, ...
        'Log contrast of fitted amplitude against local background.');
    lib(end+1) = localExpr('log_amplitude', ...
        'log10(max(amplitude + 1, 1e-6))', ...
        {'amplitude'}, ...
        'Log-compressed fitted amplitude.');
    lib(end+1) = localExpr('amp_to_intensity_ratio', ...
        'amplitude / (integrated_intensity + 1)', ...
        {'amplitude', 'integrated_intensity'}, ...
        'Peak-to-total intensity ratio.');
    lib(end+1) = localExpr('amp_quality_coupled', ...
        'r_squared * (amplitude / (background + 1))', ...
        {'r_squared', 'amplitude', 'background'}, ...
        'High when amplitude contrast and fit quality are both strong.');
    lib(end+1) = localExpr('amplitude_subtracted_background', ...
        '(amplitude - background) / (background + 1)', ...
        {'amplitude', 'background'}, ...
        'Background-corrected amplitude ratio.');
    lib(end+1) = localExpr('amplitude_shot_noise_ratio', ...
        'amplitude / sqrt(max(background, 0) + 1)', ...
        {'amplitude', 'background'}, ...
        'Amplitude normalized by Poisson-like background scale.');
    lib(end+1) = localExpr('gaussian_energy_error_2d', ...
        'abs(integrated_intensity - (2 * pi * amplitude * sigma_x * sigma_y)) / (integrated_intensity + abs(2 * pi * amplitude * sigma_x * sigma_y) + 1)', ...
        {'integrated_intensity', 'amplitude', 'sigma_x', 'sigma_y'}, ...
        'Relative mismatch between integrated intensity and 2D Gaussian energy.');
    lib(end+1) = localExpr('gaussian_energy_ratio_2d', ...
        '(2 * pi * amplitude * sigma_x * sigma_y) / (integrated_intensity + 1)', ...
        {'integrated_intensity', 'amplitude', 'sigma_x', 'sigma_y'}, ...
        '2D Gaussian energy estimate normalized by integrated intensity.');
    lib(end+1) = localExpr('gaussian_energy_consistency_score_2d', ...
        '1 / (1 + abs(integrated_intensity - (2 * pi * amplitude * sigma_x * sigma_y)) / (integrated_intensity + abs(2 * pi * amplitude * sigma_x * sigma_y) + 1))', ...
        {'integrated_intensity', 'amplitude', 'sigma_x', 'sigma_y'}, ...
        'Bounded 2D Gaussian energy-consistency score (higher is better).');
    lib(end+1) = localExpr('gaussian_energy_error_3d', ...
        'abs(integrated_intensity - (((2 * pi)^(3/2)) * amplitude * sigma_x * sigma_y * sigma_z)) / (integrated_intensity + abs(((2 * pi)^(3/2)) * amplitude * sigma_x * sigma_y * sigma_z) + 1)', ...
        {'integrated_intensity', 'amplitude', 'sigma_x', 'sigma_y', 'sigma_z'}, ...
        'Relative mismatch between integrated intensity and 3D Gaussian energy.');
    lib(end+1) = localExpr('gaussian_energy_ratio_3d', ...
        '(((2 * pi)^(3/2)) * amplitude * sigma_x * sigma_y * sigma_z) / (integrated_intensity + 1)', ...
        {'integrated_intensity', 'amplitude', 'sigma_x', 'sigma_y', 'sigma_z'}, ...
        '3D Gaussian energy estimate normalized by integrated intensity.');
    lib(end+1) = localExpr('gaussian_energy_consistency_score_3d', ...
        '1 / (1 + abs(integrated_intensity - (((2 * pi)^(3/2)) * amplitude * sigma_x * sigma_y * sigma_z)) / (integrated_intensity + abs(((2 * pi)^(3/2)) * amplitude * sigma_x * sigma_y * sigma_z) + 1))', ...
        {'integrated_intensity', 'amplitude', 'sigma_x', 'sigma_y', 'sigma_z'}, ...
        'Bounded 3D Gaussian energy-consistency score (higher is better).');

    % 1D/2D+1D amplitude consistency
    lib(end+1) = localExpr('axis_amplitude_imbalance', ...
        '(abs(amplitude_x - amplitude_y) + abs(amplitude_x - amplitude_z) + abs(amplitude_y - amplitude_z)) / (amplitude_x + amplitude_y + amplitude_z + 1)', ...
        {'amplitude_x', 'amplitude_y', 'amplitude_z'}, ...
        'Axis-wise 1D amplitude imbalance score.');
    lib(end+1) = localExpr('axis_amplitude_bg_ratio', ...
        '((amplitude_x + amplitude_y + amplitude_z) / 3) / (background + 1)', ...
        {'amplitude_x', 'amplitude_y', 'amplitude_z', 'background'}, ...
        'Mean axis amplitude relative to background.');
    lib(end+1) = localExpr('axis_amplitude_cv', ...
        'sqrt(((amplitude_x - (amplitude_x + amplitude_y + amplitude_z)/3)^2 + (amplitude_y - (amplitude_x + amplitude_y + amplitude_z)/3)^2 + (amplitude_z - (amplitude_x + amplitude_y + amplitude_z)/3)^2) / 3) / (((amplitude_x + amplitude_y + amplitude_z)/3) + 1e-3)', ...
        {'amplitude_x', 'amplitude_y', 'amplitude_z'}, ...
        'Coefficient of variation across axis-wise amplitudes.');
    lib(end+1) = localExpr('xy_z_amplitude_ratio', ...
        'amplitude_xy / (amplitude_z + 1e-3)', ...
        {'amplitude_xy', 'amplitude_z'}, ...
        '2D XY vs 1D Z amplitude balance.');
    lib(end+1) = localExpr('xy_z_amplitude_balance_log', ...
        'abs(log(max((abs(amplitude_xy) + 1e-3) / (abs(amplitude_z) + 1e-3), 1e-6)))', ...
        {'amplitude_xy', 'amplitude_z'}, ...
        'Magnitude of XY-vs-Z amplitude imbalance.');
    lib(end+1) = localExpr('xy_z_amplitude_symmetry', ...
        '1 / (1 + abs(amplitude_xy - amplitude_z) / (abs(amplitude_xy) + abs(amplitude_z) + 1e-3))', ...
        {'amplitude_xy', 'amplitude_z'}, ...
        'Higher when XY and Z amplitudes are mutually consistent.');

    % Distortion/correlation terms for distorted models
    lib(end+1) = localExpr('distortion_energy', ...
        'rho_xy^2 + rho_xz^2 + rho_yz^2', ...
        {'rho_xy', 'rho_xz', 'rho_yz'}, ...
        'Correlation distortion energy for distorted Gaussian fits.');
    lib(end+1) = localExpr('distortion_penalized_quality', ...
        'r_squared / (1 + rho_xy^2 + rho_xz^2 + rho_yz^2)', ...
        {'r_squared', 'rho_xy', 'rho_xz', 'rho_yz'}, ...
        'Fit quality penalized by strong axis correlations.');
    lib(end+1) = localExpr('distortion_magnitude', ...
        'sqrt(max(rho_xy^2 + rho_xz^2 + rho_yz^2, 0))', ...
        {'rho_xy', 'rho_xz', 'rho_yz'}, ...
        'Root-energy distortion magnitude.');
    lib(end+1) = localExpr('distortion_weighted_snr', ...
        'log10(max((integrated_intensity + 1) / (background + 1), 1e-6)) / (1 + rho_xy^2 + rho_xz^2 + rho_yz^2)', ...
        {'integrated_intensity', 'background', 'rho_xy', 'rho_xz', 'rho_yz'}, ...
        'SNR proxy penalized by distortion terms.');
    lib(end+1) = localExpr('distortion_bg_coupled', ...
        '(rho_xy^2 + rho_xz^2 + rho_yz^2) * background / (integrated_intensity + 1)', ...
        {'rho_xy', 'rho_xz', 'rho_yz', 'background', 'integrated_intensity'}, ...
        'Correlation distortion burden normalized by local signal.');
    lib(end+1) = localExpr('distortion_shape_coupled', ...
        '(rho_xy^2 + rho_xz^2 + rho_yz^2) * sigma_z_ratio', ...
        {'rho_xy', 'rho_xz', 'rho_yz', 'sigma_z_ratio'}, ...
        'Joint penalty for correlation distortion and axial elongation.');

    % Skew-specific terms (skewed models)
    lib(end+1) = localExpr('skew_energy_xy', ...
        'abs(alpha_x) + abs(alpha_y)', ...
        {'alpha_x', 'alpha_y'}, ...
        'Lateral skewness magnitude.');
    lib(end+1) = localExpr('skew_energy_xyz', ...
        'abs(alpha_x) + abs(alpha_y) + abs(alpha_z)', ...
        {'alpha_x', 'alpha_y', 'alpha_z'}, ...
        'Full 3D skewness magnitude.');
    lib(end+1) = localExpr('skew_quality_penalty_xy', ...
        'r_squared / (1 + abs(alpha_x) + abs(alpha_y))', ...
        {'r_squared', 'alpha_x', 'alpha_y'}, ...
        'Quality penalized by lateral skewness.');
    lib(end+1) = localExpr('skew_quality_penalty_xyz', ...
        'r_squared / (1 + abs(alpha_x) + abs(alpha_y) + abs(alpha_z))', ...
        {'r_squared', 'alpha_x', 'alpha_y', 'alpha_z'}, ...
        'Quality penalized by 3D skewness.');
    lib(end+1) = localExpr('distortion_skew_joint_penalty', ...
        '1 / (1 + rho_xy^2 + rho_xz^2 + rho_yz^2 + abs(alpha_x) + abs(alpha_y) + abs(alpha_z))', ...
        {'rho_xy', 'rho_xz', 'rho_yz', 'alpha_x', 'alpha_y', 'alpha_z'}, ...
        'Joint penalty score combining correlation distortion and skew asymmetry.');

    % Radial symmetry specific
    lib(end+1) = localExpr('radial_symmetry_intensity_coupled', ...
        'radial_symmetry_score * log10(max(integrated_intensity + 1, 1e-6))', ...
        {'radial_symmetry_score', 'integrated_intensity'}, ...
        'Symmetry score weighted by signal magnitude.');
    lib(end+1) = localExpr('radial_symmetry_bg_penalty', ...
        'radial_symmetry_score / (background + 1)', ...
        {'radial_symmetry_score', 'background'}, ...
        'Symmetry score penalized by local background.');
    lib(end+1) = localExpr('radial_symmetry_logit', ...
        'log10(max(radial_symmetry_score / max(1 - radial_symmetry_score, 1e-6), 1e-6))', ...
        {'radial_symmetry_score'}, ...
        'Logit-like transform emphasizing high-confidence symmetry convergence.');
    lib(end+1) = localExpr('radial_symmetry_poisson_proxy', ...
        'radial_symmetry_score * ((integrated_intensity - background) / sqrt(max(integrated_intensity + background, 1)))', ...
        {'radial_symmetry_score', 'integrated_intensity', 'background'}, ...
        'Symmetry-weighted Poisson contrast proxy.');
    lib(end+1) = localExpr('radial_symmetry_signal_fraction', ...
        'radial_symmetry_score * (integrated_intensity / (integrated_intensity + background + 1))', ...
        {'radial_symmetry_score', 'integrated_intensity', 'background'}, ...
        'Symmetry confidence coupled to local signal-purity fraction.');

    % Optional advanced stats (from augmentFitResultsWithModelStats)
    lib(end+1) = localExpr('info_gain_aic_norm', ...
        'delta_aic_flat_minus_gaussian / (abs(aic_gaussian) + 1)', ...
        {'delta_aic_flat_minus_gaussian', 'aic_gaussian'}, ...
        'Normalized AIC evidence gain for Gaussian model.');
    lib(end+1) = localExpr('info_gain_bic_norm', ...
        'delta_bic_flat_minus_gaussian / (abs(bic_gaussian) + 1)', ...
        {'delta_bic_flat_minus_gaussian', 'bic_gaussian'}, ...
        'Normalized BIC evidence gain for Gaussian model.');
    lib(end+1) = localExpr('lrt_stat_log', ...
        'log10(max(lrt_stat_flat_vs_gaussian + 1, 1e-6))', ...
        {'lrt_stat_flat_vs_gaussian'}, ...
        'Log-likelihood-ratio evidence against flat model.');
    lib(end+1) = localExpr('poisson_advantage_norm', ...
        'delta_nll_poisson_flat_minus_gaussian / (abs(nll_poisson_gaussian) + 1)', ...
        {'delta_nll_poisson_flat_minus_gaussian', 'nll_poisson_gaussian'}, ...
        'Normalized Poisson NLL advantage for Gaussian model.');
    lib(end+1) = localExpr('bic_posterior_like_weight', ...
        '1 / (1 + exp(-0.5 * delta_bic_flat_minus_gaussian))', ...
        {'delta_bic_flat_minus_gaussian'}, ...
        'Sigmoid-transformed BIC evidence proxy for Gaussian-model preference.');
    lib(end+1) = localExpr('aic_posterior_like_weight', ...
        '1 / (1 + exp(-0.5 * delta_aic_flat_minus_gaussian))', ...
        {'delta_aic_flat_minus_gaussian'}, ...
        'Sigmoid-transformed AIC evidence proxy for Gaussian-model preference.');
    lib(end+1) = localExpr('evidence_consensus_weight', ...
        '(1 / (1 + exp(-0.5 * delta_bic_flat_minus_gaussian))) * (1 / (1 + exp(-0.5 * delta_aic_flat_minus_gaussian)))', ...
        {'delta_bic_flat_minus_gaussian', 'delta_aic_flat_minus_gaussian'}, ...
        'Consensus evidence score requiring both AIC and BIC support.');
    lib(end+1) = localExpr('poisson_evidence_weight', ...
        '1 / (1 + exp(-delta_nll_poisson_flat_minus_gaussian))', ...
        {'delta_nll_poisson_flat_minus_gaussian'}, ...
        'Sigmoid-transformed Poisson likelihood evidence for Gaussian over flat.');
    lib(end+1) = localExpr('residual_robustness_ratio', ...
        'residual_std / (residual_mad + 1e-6)', ...
        {'residual_std', 'residual_mad'}, ...
        'Residual Gaussianity proxy via STD/MAD ratio.');
    lib(end+1) = localExpr('residual_shape_penalty', ...
        'abs(residual_skewness) + abs(residual_kurtosis_excess)', ...
        {'residual_skewness', 'residual_kurtosis_excess'}, ...
        'Residual non-normality penalty.');
    lib(end+1) = localExpr('residual_quality_joint', ...
        'r_squared / (residual_over_signal + 1e-6)', ...
        {'r_squared', 'residual_over_signal'}, ...
        'High for accurate fits with small residual relative to signal.');
    lib(end+1) = localExpr('model_evidence_quality', ...
        'r_squared * log10(max(abs(delta_bic_flat_minus_gaussian) + 1, 1e-6))', ...
        {'r_squared', 'delta_bic_flat_minus_gaussian'}, ...
        'Couples fit quality to model-selection evidence magnitude.');
    lib(end+1) = localExpr('residual_normality_logp', ...
        '-log10(max(normality_ks_pvalue, 1e-12))', ...
        {'normality_ks_pvalue'}, ...
        'Strength of residual non-normality evidence.');
    lib(end+1) = localExpr('evidence_residual_ratio', ...
        'delta_bic_flat_minus_gaussian / (abs(residual_std) + 1e-6)', ...
        {'delta_bic_flat_minus_gaussian', 'residual_std'}, ...
        'Model evidence normalized by residual scale.');
    lib(end+1) = localExpr('robust_bias_ratio', ...
        'abs(residual_mean) / (residual_mad + 1e-6)', ...
        {'residual_mean', 'residual_mad'}, ...
        'Residual bias normalized by robust dispersion.');
    lib(end+1) = localExpr('aic_bic_agreement', ...
        'abs(delta_aic_flat_minus_gaussian - delta_bic_flat_minus_gaussian) / (abs(delta_bic_flat_minus_gaussian) + 1)', ...
        {'delta_aic_flat_minus_gaussian', 'delta_bic_flat_minus_gaussian'}, ...
        'Agreement between AIC and BIC evidence signals.');
    lib(end+1) = localExpr('residual_gaussianity_score', ...
        '1 / (1 + abs(residual_skewness) + abs(residual_kurtosis_excess) + abs(residual_mean) / (residual_mad + 1e-6))', ...
        {'residual_skewness', 'residual_kurtosis_excess', 'residual_mean', 'residual_mad'}, ...
        'Bounded residual-shape score favoring centered, near-Gaussian residuals.');
    lib(end+1) = localExpr('evidence_quality_consensus', ...
        'r_squared * (1 / (1 + exp(-0.5 * delta_bic_flat_minus_gaussian))) * (1 / (1 + exp(-0.5 * delta_aic_flat_minus_gaussian)))', ...
        {'r_squared', 'delta_bic_flat_minus_gaussian', 'delta_aic_flat_minus_gaussian'}, ...
        'Evidence-consensus score weighted by fit quality.');
    lib(end+1) = localExpr('model_evidence_residual_purity', ...
        '(delta_bic_flat_minus_gaussian + delta_aic_flat_minus_gaussian) / (abs(residual_std) + abs(residual_mean) + 1)', ...
        {'delta_bic_flat_minus_gaussian', 'delta_aic_flat_minus_gaussian', 'residual_std', 'residual_mean'}, ...
        'Joint model-evidence score penalized by residual scale and bias.');
end

function entry = localExpr(name, expression, requiredFeatures, rationale)
    entry = struct();
    entry.name = name;
    entry.expression = localVectorizeOperators(expression);
    entry.requiredFeatures = requiredFeatures;
    entry.rationale = rationale;
end

function exprOut = localVectorizeOperators(exprIn)
    exprOut = char(string(exprIn));
    exprOut = regexprep(exprOut, '(?<!\.)\^', '.^');
    exprOut = regexprep(exprOut, '(?<!\.)\*', '.*');
    exprOut = regexprep(exprOut, '(?<!\.)/(?!/)', './');
end

function refs = localLiteratureReferences()
    refs = { ...
        'Thompson, Larson, Webb (2002) Precise nanometer localization analysis for individual fluorescent probes.', ...
        'Ober, Ram, Ward (2004) Localization accuracy in single-molecule microscopy.', ...
        'Mortensen et al. (2010) Optimized localization analysis for single-molecule tracking and super-resolution microscopy.', ...
        'Chao et al. (2016) Fisher information theory for parameter estimation in single-molecule microscopy.', ...
        'Sage et al. (2015) Super-resolution fight club: assessment of 2D/3D localization software.', ...
        'Akaike (1974) A new look at the statistical model identification.', ...
        'Schwarz (1978) Estimating the dimension of a model (BIC).', ...
        'Burnham and Anderson (2002) Model Selection and Multimodel Inference.', ...
        'Hampel et al. (1986) Robust Statistics: The Approach Based on Influence Functions.' ...
    };
end
