function names = getModelStatsFeatureNames()
% getModelStatsFeatureNames - Canonical list of optional model-stat fields.
%
% These fields are produced by snap_contrib.svm.augmentFitResultsWithModelStats
% when raw fit windows are available.

    names = { ...
        'aic_gaussian', ...
        'bic_gaussian', ...
        'aic_flat', ...
        'bic_flat', ...
        'delta_aic_flat_minus_gaussian', ...
        'delta_bic_flat_minus_gaussian', ...
        'nll_poisson_gaussian', ...
        'nll_poisson_flat', ...
        'delta_nll_poisson_flat_minus_gaussian', ...
        'lrt_stat_flat_vs_gaussian', ...
        'residual_mean', ...
        'residual_std', ...
        'residual_mad', ...
        'residual_skewness', ...
        'residual_kurtosis_excess', ...
        'residual_over_signal', ...
        'normality_ks_pvalue' ...
    };
end
